### ISSUE TITLE
Should User ID be a String vs. Number?

### ISSUE THREAD

**Issue by metaskills** [getzep/zep-js#109]
When I have a user object, and pass the `id` property to `addSession` like so:

```typescript
zep.memory.addSession({
  sessionId: sessionId,
  userId: user.id,
});
```

I get the following error:

```
Type 'number | undefined' is not assignable to type 'string'.
Type 'undefined' is not assignable to type 'string'. ts(2322)
• CreateSessionRequest.d.ts(20, 5): The expected type comes from property
'userId' which is declared here on type 'CreateSessionRequest'
```

Should this be a string? https://github.com/getzep/zep-js/blob/main/src/api/types/User.ts#L10

**Comment by metaskills** [comment]
Ah, I'm guessing I should use the `userId` property.

**Comment by jackaldenryan** [comment]
Hi, thank you for bringing this to our attention, since the `id` field would seem confusing here. 

It looks like using `userId: user.userId!` should work, assuming you have a setup like this:

```
const userId = "typescript-test-user1";
const sessionId = "typescript-test-session1";
const user = await client.user.add({userId: userId});
const session = await client.memory.addSession({
    sessionId: sessionId,
    userId: user.userId!,
});
```

Let us know if this works for you.
