### ISSUE TITLE
Specify minimum node version

### ISSUE THREAD

**Issue by moltar** [getzep/zep-js#33]
I think a minimum of 18 is needed, given that I got an error with v16.

```
❯ npm start

> zep-client@1.0.0 start
> tsx index.ts

/.../zep/client/node_modules/@getzep/zep-js/dist/zep-client.js:157
            const response = yield fetch(healthCheckURL, { headers: this.headers });
                             ^

ReferenceError: fetch is not defined
```

And on `18.12.1`, I get:

```
(node:86658) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
```

---

Alternatively, can install [`undici`](https://github.com/nodejs/undici) as a dep, which is part of Node now, and is the basis on which native Node fetch is built.

Additional info on fetch: https://nodejs.org/en/blog/announcements/v18-release-announce#new-globally-available-browser-compatible-apis

**Comment by danielchalef** [comment]
Thanks for reporting this. Fixed!
