### ISSUE TITLE
Errors in README - Missing Exports and Invalid Package Name

### ISSUE THREAD

**Issue by josiahbryan** [getzep/zep-js#6]
Hey guys!

I think your README is out of date here.

Given this first line:
```javascript
import {ZepClient, Memory, Message, SearchPayload, SearchResult, ZepClientError, UnexpectedResponseError} from "zep-js";
```

1. Package name should be `from "@getzep/zep-js"` not "zep-js"
2. BIG PROBLEM: `SearchPayload`, `SearchResult`, and `ZepClientError` are not exported from the `@getzep/zep-js` package

Regarding the #2 problem there, this is what happens if I try to import something like `SearchPaylod` from `@getzep/zep-js`:

```
SyntaxError: The requested module 'file:///Users/josiahbryan/devel/rubber/backend/node_modules/@getzep/zep-js/dist/index.js' does not provide an export named 'SearchResult'
```

**Comment by rsharath** [comment]
SearchPayload, SearchResult have been renamed to MemorySearchPayload and MemorySearchResult
ZepClientError has been expanded to UnexpectedResponseError, NotFoundError and AuthenticationError

Will catch up the README.

**Comment by josiahbryan** [comment]
Hey great! You might also want to show some TLC to https://docs.getzep.com/sdk/#persisting-a-memory-to-a-session as it also show the same out-of-date mentions:

1. Wrong package name (zep-js)
2. Uses `SearchPayload`

**Comment by danielchalef** [comment]
Thanks for the heads up. We've been moving quickly since we launched late May and docs have needed some updating.

**Comment by rsharath** [comment]
@josiahbryan fixed, closing the issue.
